-- Initial alcoLoco schema (SPEC.md §4 and §7).
--
-- Conventions applied to every table below:
--
--   * primary keys are of type `uuid` and hold a **UUID v7 generated by the
--     application** (crate `uuid`, feature `v7`). PostgreSQL 16 ships no native
--     `uuidv7()`, so no column has a default: the caller always supplies the
--     identifier. v7 is time ordered, which makes it directly usable as a
--     pagination cursor;
--   * every point in time is a `timestamptz` stored in UTC. No local time and no
--     naive timestamp ever reaches the database (SPEC.md §7);
--   * durations are whole seconds in an `integer` column suffixed `_seconds`.
--     `interval` would allow month-based values, which have no meaning here and
--     are awkward to map back to the `f64` seconds the computation engine uses;
--   * volumes are millilitres (`_ml`), the unit of the reference formula of
--     SPEC.md §6.1. The cL / % choice offered to the user is a presentation and
--     input concern carried by `quantity_unit`;
--   * physical quantities are `double precision`, the exact type the computation
--     engine works in, so that a stored value round-trips bit for bit and the
--     "deterministic and replayable" requirement of SPEC.md §7 holds;
--   * there is deliberately **no `beta` column**: the elimination rate is a
--     constant of the `domain` crate, neither profile data nor an API field
--     (SPEC.md §10.0-H);
--   * no age is stored anywhere: `profile_settings_version` carries the birth
--     date and the age is derived at ingestion time (SPEC.md §10.0-K).

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

-- Sexes distinguished by the Watson equations (SPEC.md §6.2). The model has
-- exactly two branches, hence exactly two values.
CREATE TYPE sex AS ENUM ('male', 'female');

-- How the quantity of every component of a drink is expressed. The choice is
-- made per drink (SPEC.md §5.3).
CREATE TYPE quantity_unit AS ENUM ('cl', 'percent');

-- SPEC.md §5.4: the base library holds alcohols and soft drinks.
CREATE TYPE library_item_category AS ENUM ('alcohol', 'soft');

-- ---------------------------------------------------------------------------
-- Shared triggers
-- ---------------------------------------------------------------------------

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
    'Keeps updated_at truthful whatever the writer, instead of trusting every caller.';

-- ---------------------------------------------------------------------------
-- profile
-- ---------------------------------------------------------------------------
--
-- Identity plus the input preferences. The physiological parameters (weight,
-- height, sex, birth date) live in `profile_settings_version` and nowhere else:
-- they are exactly the versioned parameters, and duplicating a "current" copy
-- here would create two sources of truth able to contradict each other. The
-- current values of a profile are the ones of `profile_settings_at(id, now())`,
-- which the deferred constraint triggers below keep non-empty for every profile
-- that exists — under ordinary DML, and with the reservations spelled out where
-- those triggers are declared.
--
-- Input preferences are *not* versioned (SPEC.md §10.0-J): they enter no
-- computation, only the pre-filling of the entry form, so they stay here.

CREATE TABLE profile (
    id uuid PRIMARY KEY,
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    default_quantity_unit quantity_unit NOT NULL,
    default_ingestion_duration_seconds integer NOT NULL
        CHECK (default_ingestion_duration_seconds >= 0),
    default_absorption_duration_seconds integer NOT NULL
        CHECK (default_absorption_duration_seconds > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE profile IS
    'Predefined profile (no authentication in V1): identity and non-versioned input preferences.';
COMMENT ON COLUMN profile.id IS 'UUID v7 generated by the application.';
COMMENT ON COLUMN profile.default_absorption_duration_seconds IS
    'Strictly positive: a null absorption duration degenerates the trapezoidal profile of SPEC.md §6.4.';

CREATE TRIGGER profile_set_updated_at
    BEFORE UPDATE ON profile
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- profile_settings_version
-- ---------------------------------------------------------------------------
--
-- Time-stamped snapshot of the physiological parameters of a profile.
--
-- "No overlap and no gap" (SPEC.md §5.1, §10.0-J) is obtained structurally
-- rather than by a constraint: a version stores its **lower bound only**. The
-- upper bound of a version is the `valid_from` of the next one, so two versions
-- can neither overlap nor leave a hole by construction — the schema simply
-- cannot represent either. `UNIQUE (profile_id, valid_from)` completes the
-- picture by forbidding two versions starting at the very same instant, which
-- is the only remaining way to make the sequence ambiguous.
--
-- The oldest version has an open lower bound: `profile_settings_at()` below
-- falls back to it for any instant earlier than the whole sequence, so a drink
-- ingested before any recorded change always finds an applicable version.
--
-- Two rules are deliberately left out of this migration and belong to the write
-- policy of issue #7:
--   * `valid_from` may not be in the future (SPEC.md §5.1, §10.0-J). A CHECK
--     cannot express it, since it may not call `now()`, but a BEFORE
--     INSERT/UPDATE trigger could — the file already creates three triggers.
--     Not enforcing it here is a scope choice, not a PostgreSQL limitation:
--     until #7 lands, a future `valid_from` is accepted by the database;
--   * posting a version at T replaces every version strictly later than T
--     (SPEC.md §5.1).

CREATE TABLE profile_settings_version (
    id uuid PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    valid_from timestamptz NOT NULL,
    weight_kg double precision NOT NULL CHECK (weight_kg > 0 AND weight_kg < 1000),
    height_cm double precision NOT NULL CHECK (height_cm > 0 AND height_cm < 300),
    sex sex NOT NULL,
    birth_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT profile_settings_version_unique_start UNIQUE (profile_id, valid_from)
);

COMMENT ON TABLE profile_settings_version IS
    'Versioned physiological parameters. A version stores its lower bound only; the upper bound is the next valid_from.';
COMMENT ON COLUMN profile_settings_version.valid_from IS
    'Effective date supplied by the user (SPEC.md §10.0-J); may be retroactive, never in the future — a rule enforced by the write policy of issue #7, not by this schema.';
COMMENT ON COLUMN profile_settings_version.birth_date IS
    'Birth date, not an age: the age used by Watson is computed at the ingestion time of each drink (SPEC.md §10.0-K).';

-- ---------------------------------------------------------------------------
-- Every profile has at least one settings version
-- ---------------------------------------------------------------------------
--
-- Weight, height, sex and birth date are all mandatory (SPEC.md §10.0-D). Since
-- they live in `profile_settings_version`, "mandatory" means a profile must
-- always own at least one version. A plain foreign key cannot express that
-- without a cycle, so the guarantee is a DEFERRABLE constraint trigger checked
-- at commit: the profile and its first version are inserted in the same
-- transaction (the profile first, its foreign key is immediate), and the check
-- only fires once both statements have run.
--
-- Four writes can leave a profile with no version at all, and the three
-- triggers below cover the four: inserting the profile itself, deleting its
-- last version, moving that last version to another profile with an UPDATE of
-- `profile_id`, and renumbering the profile itself with an UPDATE of
-- `profile.id`. `COPY` and `MERGE`, including its update and delete branches,
-- fire the very same row triggers, so they need no declaration of their own.
-- One write only looks like a hole: deleting the profile cascades its versions
-- away and the function returns early once the profile itself is gone.
--
-- Renumbering is the one that needs a trigger of its own, and why is worth
-- writing down. The foreign key does refuse it, but only **while a version
-- still points at the old id**: it is NO ACTION on update, so once the versions
-- are gone it has nothing left to object to. A single transaction deleting
-- every version of a profile and then renumbering that profile committed
-- without a word — `assert_profile_settings_version_present()` returns early
-- because the old id names no profile any more, and the deferred check looks
-- for that same old id at COMMIT. `profile_keeps_its_id` refuses the
-- renumbering itself, with no qualifier attached.
--
-- Which of the two mechanisms actually rejects was measured here rather than
-- assumed, and it is not the one the division of labour suggests.
-- `profile_keeps_its_id` is a BEFORE ROW trigger and a foreign key is checked
-- after the row is written, so the trigger fires first and rejects **both**
-- branches, on the spot, with SQLSTATE 23000 and `profile ... may not be
-- renumbered to ...`. The foreign key stands behind it and still covers only
-- the one branch: with the trigger disabled, renumbering a profile a version
-- still points at is refused by `profile_settings_version_profile_id_fkey`
-- with SQLSTATE 23503, while renumbering one whose versions have just been
-- deleted commits and reopens the hole. The trigger is therefore what closes
-- the path; the foreign key is a partial second line, and the message a caller
-- sees is always the trigger's.
--
-- An UPDATE that does not name `id` never reaches the trigger, which is
-- declared `OF id`, and `UPDATE profile SET id = id` passes: it compares
-- values, not the shape of the SET list.
--
-- Scope of the guarantee, stated so that it can be checked rather than
-- believed. SPEC.md §10.0-L is the source of truth for it and delegates the
-- exact reach of each class to this file; classes (a) to (d) below are its
-- four classes, in the same order. Class (e) is one more, found here and not
-- listed there; it is closed, so it costs SPEC.md nothing, but the count no
-- longer matches on purpose.
--
-- What holds: a transaction **running alone** that would leave an existing
-- profile without a version does not commit. It holds that way for `INSERT`,
-- `UPDATE`, `DELETE`, `COPY` and `MERGE`. Two of the three triggers enforce it
-- at `COMMIT`; the third, `profile_keeps_its_id`, has nothing to wait for and
-- rejects on the spot. The write order inside such a transaction is not free
-- for all that: the profile must precede its first version.
-- `profile_settings_version_profile_id_fkey` is **not** DEFERRABLE, so the
-- reverse order is refused **on the spot** with
-- SQLSTATE 23503, not at commit, and `SET CONSTRAINTS ALL DEFERRED` changes
-- nothing to it — that statement can only defer a constraint declared
-- deferrable. What defers here is the pair of constraint triggers below, and
-- nothing else.
--
-- The guarantee does **not** hold in the five classes below. They are stated
-- as classes and not as a closed list of paths, a closed list being false
-- again at the next path — class (e) is the proof of that, found after the
-- first four were written down as if they covered the ground. Each was
-- reproduced against PostgreSQL 16 on this schema rather than deduced from
-- the manual. Four of the five are open; (e) is closed, by this file, and is
-- kept here because a taxonomy that drops a class once it is closed teaches
-- the next reader the same blind spot.
--
--   (a) `TRUNCATE profile_settings_version` empties the table and leaves the
--       profiles standing. It walks no row, so no `FOR EACH ROW` trigger runs,
--       and this schema declares no `AFTER TRUNCATE` trigger. PostgreSQL
--       refuses a truncation only when a foreign key in *another* table points
--       at the truncated one: `TRUNCATE profile` is indeed refused, `TRUNCATE
--       profile_settings_version` is not, since the reference runs the other
--       way. It takes the TRUNCATE privilege;
--   (b) anything that switches the triggers off or takes them away:
--       `SET session_replication_role = replica`, which wants superuser or,
--       since PostgreSQL 15, a `GRANT SET ON PARAMETER
--       session_replication_role TO <role>`, and which also disables genuine
--       foreign keys, and `ALTER TABLE <table> DISABLE TRIGGER USER` or `DROP
--       TRIGGER`, which want table ownership and leave the foreign keys
--       enforcing — an orphan version is still rejected while
--       the constraint triggers are off, which makes them the narrower bypass.
--       Whichever table is unguarded decides which hole opens: `profile` lets
--       a versionless profile be inserted, `profile_settings_version` lets the
--       last version be deleted;
--   (c) inside the writing transaction, between the statement and the
--       `COMMIT`. The check is deferred to commit, and the price of deferring
--       it is that the writing transaction reads its own intermediate state:
--       `profile_settings_at()` returns no row there for a profile whose
--       versions it has just deleted, while the profile itself is still
--       visible. Nothing durable comes of it: either the profile is still at
--       zero versions at `COMMIT` and the `COMMIT` is refused, or the
--       transaction has put a version back and commits on a consistent state;
--   (d) under concurrency, and this one is not confined to the writing
--       transaction. Two transactions each deleting a *different* version of
--       the same profile both commit without error — each still sees the
--       version the other is removing, so neither trigger finds the profile
--       empty — and the profile is left durably at zero versions. This is the
--       nominal regime: it holds at PostgreSQL's default isolation level and
--       at the one the backend driver uses. The only pair measured to be
--       refused outright is two transactions both committing at SERIALIZABLE
--       (40001); outside of it what decides is how far the two commit windows
--       overlap, rather than the isolation level of either committer. Measured
--       during the arbitration of #2, 20 profiles of 2 versions per pair, on
--       fresh databases, both COMMITs synchronised on an absolute server
--       instant: READ COMMITTED x READ COMMITTED violates 20/20 at an offset
--       of 0 and of 2 ms but 0/20 at 20 ms; REPEATABLE READ x REPEATABLE READ
--       violates 20/20 even at 100 ms; SERIALIZABLE x SERIALIZABLE 0/20; and
--       SERIALIZABLE committing first against READ COMMITTED committing last
--       at 50 ms, 0/20. Those campaigns are not this file's, which reports
--       them. SPEC.md §10.0-L states the same reservation and phrases the
--       decision in terms of the isolation level of the last committer; the
--       figures above are the finer measurement, and #43, which carries the
--       real fix for this class, aligns that line when it closes;
--   (e) `pg_temp` shadowing — **closed by this file**, and open to any role
--       able to write until it was. `search_path` searches `pg_temp` before
--       `public`, and the `TEMP` privilege on a database is held by `PUBLIC`
--       by default, so a role granted nothing beyond SELECT, INSERT, UPDATE
--       and DELETE can run `CREATE TEMP TABLE profile (id uuid)` and have a
--       function that reads `profile` unqualified read *that* table. An empty
--       temporary `profile` makes the early return of
--       `assert_profile_settings_version_present()` fire on every call, which
--       turns all three constraint triggers into no-ops at once: deleting
--       every version of a profile then commits without error and leaves it
--       durably versionless. Shadowing `profile_settings_version` the same
--       way feeds a fabricated weight, height, sex and birth date into every
--       `profile_settings_at()` answer, hence into every computed curve —
--       this class reaches the values, not only their presence, which none of
--       the other four do. What closes it is schema qualification: the two
--       function bodies below name `public.profile` and
--       `public.profile_settings_version`, and a name written with its schema
--       consults no `search_path` at all. Qualification rather than a `SET
--       search_path` clause on the functions, which would close it just as
--       well: `SET` makes a SQL-language function opaque to the inliner, and
--       `profile_settings_at()` is on the hot path of every curve query. The
--       trigger function is qualified too, for one technique in the file
--       rather than two. Any function added here later reads relations
--       schema-qualified for the same reason.
--
-- Classes (a), (b) and (d) leave a durably inconsistent state, in which
-- `profile_settings_at()` returns no row for a profile that still exists and
-- signals nothing. Class (c) leaves none: the empty reading is confined to the
-- writing transaction. Whether that transaction is refused depends on the state
-- it reaches at `COMMIT`, not on its having passed through an empty one — one
-- that deletes every version of a profile and then inserts another commits
-- normally, durably, on a consistent state. What class (c) costs is a
-- misleading intermediate read, not a durable hole.
--
-- Which role reaches which class, since the answer is not the same for all
-- five. (a) needs the TRUNCATE privilege and (b) needs superuser, ownership of
-- the table, or a `GRANT SET ON PARAMETER session_replication_role`: an
-- application role holding only DML grants reaches neither of those two, and
-- both belong to a restore, a fixture reset or a bulk import rather than to
-- the application's ordinary writes. That is a statement about (a) and (b)
-- alone, and it must not be read as "DML grants are harmless": (c), (d) and
-- (e) are the opposite case. (c) and (d) are plain DML, so **any** role able
-- to write reaches them, the application's own role first. (e) needed no DML
-- privilege at all beyond the `TEMP` one every role holds by default, and it
-- was the widest of the five while it was open — a DML-only role reached the
-- durable hole of (a) and (b) through it, without either of their privileges,
-- and reached the returned values on top. Schema qualification is what closes
-- it; no grant does, since none of them can be revoked far enough to matter
-- while `REVOKE TEMPORARY ON DATABASE ... FROM PUBLIC` stays untypical.
-- Checked on this schema with a role granted only SELECT, INSERT, UPDATE and
-- DELETE: `TRUNCATE` and `ALTER TABLE ... DISABLE TRIGGER USER` are both
-- refused, while `BEGIN; DELETE ...; SELECT count(*) FROM
-- profile_settings_at(...)` answers 0 for a profile that still exists, two
-- concurrent such `DELETE`s on different versions of one profile both commit,
-- and `CREATE TEMP TABLE profile (id uuid)` succeeds for that same role —
-- after which both shadowing attacks of (e) are refused by the qualified
-- bodies below, where before the fix both went through. The local development
-- role owns these tables and is superuser, so the four open classes are all
-- within its reach.
--
-- Consequence for whoever writes #7, #16 or any other reader of a profile's
-- settings: **this invariant cannot be relied on in the presence of concurrent
-- writes** for as long as #43 is open. Treat `profile_settings_at()` as
-- returning zero or one row and handle the empty case; do not infer that a
-- version exists from the fact that the profile does. #43 carries the real fix
-- and blocks #7.

CREATE FUNCTION assert_profile_settings_version_present() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    target_profile uuid;
BEGIN
    IF TG_OP = 'INSERT' THEN
        target_profile := NEW.id;
    ELSE
        target_profile := OLD.profile_id;
    END IF;

    -- Both relations are read schema-qualified, and must stay that way: an
    -- unqualified `profile` resolves through `search_path`, which reaches
    -- `pg_temp` first, and an empty temporary table of that name makes the
    -- early return below fire on every call — class (e) above.

    -- The profile itself is gone (its versions were cascaded away): nothing to
    -- guarantee any more.
    IF NOT EXISTS (SELECT 1 FROM public.profile WHERE id = target_profile) THEN
        RETURN NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM public.profile_settings_version WHERE profile_id = target_profile
    ) THEN
        RAISE EXCEPTION 'profile % has no settings version', target_profile
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER profile_requires_settings_version
    AFTER INSERT ON profile
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_profile_settings_version_present();

CREATE CONSTRAINT TRIGGER profile_settings_version_keeps_last
    AFTER DELETE OR UPDATE OF profile_id ON profile_settings_version
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_profile_settings_version_present();

CREATE FUNCTION assert_profile_id_unchanged() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.id IS DISTINCT FROM OLD.id THEN
        RAISE EXCEPTION 'profile % may not be renumbered to %', OLD.id, NEW.id
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION assert_profile_id_unchanged() IS
    'Keeps profile.id immutable: a renumbering hides the profile from the deferred settings-version check.';

CREATE TRIGGER profile_keeps_its_id
    BEFORE UPDATE OF id ON profile
    FOR EACH ROW EXECUTE FUNCTION assert_profile_id_unchanged();

-- ---------------------------------------------------------------------------
-- Settings applicable at a given instant
-- ---------------------------------------------------------------------------
--
-- It returns the latest version starting at or before `at`, and falls back to
-- the oldest version of the profile otherwise — that is the open lower bound of
-- SPEC.md §5.1. Combined with the constraint triggers above, it returns a row
-- for every profile that exists and every non-NULL `at` — as far as those
-- triggers reach, which the paragraph declaring them delimits.
--
-- A NULL argument returns **no row** rather than a fallback one: `valid_from <=
-- NULL` is NULL, which would empty the FILTER and silently fall back to the
-- oldest version — that is, answer an unknown instant with real settings. An
-- unknown profile returns no row for the same reason of honesty.
--
-- `SETOF` is what makes "no row" expressible. A function declared `RETURNS
-- profile_settings_version` returns a composite, and a composite whose SQL body
-- yields nothing is NULL — which reads as NULL in scalar position but expands
-- to **one row of NULLs** in `FROM` position, the position a caller uses. A
-- caller asking for the settings of an unknown profile would then receive a
-- fictitious row instead of an empty result. `SETOF ... ROWS 1` returns zero or
-- one row in both positions; at most one row can ever come out, since the inner
-- query pins a single `valid_from` and `UNIQUE (profile_id, valid_from)` makes
-- it unique. The price of `SETOF` is that the function is set-returning in the
-- select list too, and that price has three parts, not one. The known one:
-- `SELECT (profile_settings_at(...)).weight_kg` yields zero rows rather than
-- one NULL when there is no applicable version. Two more come with it, both
-- checked against PostgreSQL 16 on this schema:
--
--   * that scalar spelling is not merely row-less, it is **illegal** in
--     `WHERE`, in a `JOIN ... ON` condition, in `CASE`, and as the argument of
--     an aggregate. PostgreSQL refuses the query outright ("set-returning
--     functions are not allowed in WHERE", and its three siblings), and it
--     refuses at parse time — so the refusal does not depend on whether an
--     applicable version exists;
--   * in the select list, where the spelling *is* accepted, an empty result
--     removes **the whole row** of the enclosing query rather than just that
--     column. `SELECT p.id, (profile_settings_at(p.id, NULL)).weight_kg FROM
--     profile p` returns no row at all for a valid profile that does own a
--     version, because a NULL instant yields no row; the `p.id` the caller
--     expected to see goes with it.
--
-- Hence the calling form: `SELECT * FROM profile_settings_at($1, $2)`, or
-- `LEFT JOIN LATERAL profile_settings_at(p.id, $2) s ON true` when a row of the
-- enclosing query has to survive an empty result.

-- `profile_settings_version` is read schema-qualified here for the reason
-- given as class (e) above: unqualified, a temporary table of that name shadows
-- it and feeds fabricated physiological parameters into every computed curve.
-- Qualification and not a `SET search_path` clause, deliberately: `SET` would
-- make this function opaque to the inliner, and it runs once per curve query.
CREATE FUNCTION profile_settings_at(target_profile uuid, at timestamptz)
RETURNS SETOF public.profile_settings_version
LANGUAGE sql STABLE ROWS 1 AS $$
    SELECT v.*
    FROM public.profile_settings_version AS v
    WHERE target_profile IS NOT NULL
      AND at IS NOT NULL
      AND v.profile_id = target_profile
      AND v.valid_from = (
          SELECT coalesce(
              max(w.valid_from) FILTER (WHERE w.valid_from <= at),
              min(w.valid_from)
          )
          FROM public.profile_settings_version AS w
          WHERE w.profile_id = target_profile
      );
$$;

COMMENT ON FUNCTION profile_settings_at(uuid, timestamptz) IS
    'Physiological parameters in force at a given instant; falls back to the oldest version (open lower bound). Returns zero or one row: no row for an unknown profile or a NULL instant.';

-- ---------------------------------------------------------------------------
-- event
-- ---------------------------------------------------------------------------

CREATE TABLE event (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT event_ends_after_it_starts CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

COMMENT ON COLUMN event.ends_at IS
    'NULL for an open-ended event; the curve window is then min(now(), ends_at) + 3 h (SPEC.md §10.3).';

CREATE TRIGGER event_set_updated_at
    BEFORE UPDATE ON event
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- event_participant
-- ---------------------------------------------------------------------------
--
-- Pure association: its identity is the pair, so it carries no surrogate uuid.

CREATE TABLE event_participant (
    event_id uuid NOT NULL REFERENCES event (id) ON DELETE CASCADE,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    joined_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, profile_id)
);

CREATE INDEX event_participant_by_profile_idx ON event_participant (profile_id);

-- ---------------------------------------------------------------------------
-- drink
-- ---------------------------------------------------------------------------
--
-- A drink always belongs to the history of a profile; the link to an event is
-- optional (SPEC.md §4). The composite foreign key towards `event_participant`
-- states the stronger rule: when a drink *is* attached to an event, its profile
-- takes part in that event. It uses MATCH SIMPLE, so a NULL `event_id` skips the
-- check entirely — exactly the "optional attachment" semantics. Removing the
-- participant (or deleting the event, which cascades to the participants)
-- detaches the drinks instead of destroying them.

CREATE TABLE drink (
    id uuid PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    event_id uuid,
    name text NOT NULL CHECK (btrim(name) <> ''),
    ingested_at timestamptz NOT NULL,
    ingestion_duration_seconds integer NOT NULL CHECK (ingestion_duration_seconds >= 0),
    absorption_duration_seconds integer NOT NULL CHECK (absorption_duration_seconds > 0),
    quantity_unit quantity_unit NOT NULL,
    volume_total_ml double precision CHECK (volume_total_ml > 0),
    feeling_rating smallint CHECK (feeling_rating BETWEEN 1 AND 10),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    -- SPEC.md §10.0-A: the total volume is mandatory as soon as quantities are
    -- expressed in %, and is otherwise *derived* from the sum of the components.
    -- Forbidding it in the cL case is what makes "never entered twice, never
    -- stored contradictory" a property of the schema rather than a convention.
    CONSTRAINT drink_volume_total_matches_unit CHECK (
        (quantity_unit = 'percent' AND volume_total_ml IS NOT NULL)
        OR (quantity_unit = 'cl' AND volume_total_ml IS NULL)
    ),

    CONSTRAINT drink_belongs_to_an_event_participant
        FOREIGN KEY (event_id, profile_id)
        REFERENCES event_participant (event_id, profile_id)
        ON DELETE SET NULL (event_id)
);

COMMENT ON COLUMN drink.volume_total_ml IS
    'Mandatory when quantity_unit = percent, NULL when cl (derived from the components) — SPEC.md §10.0-A.';
COMMENT ON COLUMN drink.feeling_rating IS
    'Optional feeling rating, 1 to 10 (SPEC.md §5.9). The 1-6 cap only applies to the value suggested by the app.';

CREATE INDEX drink_profile_history_idx ON drink (profile_id, ingested_at DESC);
CREATE INDEX drink_by_event_idx ON drink (event_id, profile_id);

CREATE TRIGGER drink_set_updated_at
    BEFORE UPDATE ON drink
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- drink_component
-- ---------------------------------------------------------------------------
--
-- Name, alcohol by volume and quantity (SPEC.md §4). In V1 a component typed by
-- hand is persisted in its drink only, with no personal library (SPEC.md §10.2),
-- so the name and the degree are copied here rather than referenced.

CREATE TABLE drink_component (
    id uuid PRIMARY KEY,
    drink_id uuid NOT NULL REFERENCES drink (id) ON DELETE CASCADE,
    sort_order integer NOT NULL CHECK (sort_order >= 0),
    name text NOT NULL CHECK (btrim(name) <> ''),
    abv_percent double precision NOT NULL CHECK (abv_percent >= 0 AND abv_percent <= 100),
    quantity double precision NOT NULL CHECK (quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT drink_component_unique_order UNIQUE (drink_id, sort_order)
);

COMMENT ON COLUMN drink_component.sort_order IS
    'Order in which the component was added. Breaks ties between equal volumes when naming a drink (SPEC.md §5.3, mode 2).';
COMMENT ON COLUMN drink_component.quantity IS
    'Millilitres when the parent drink is in cl, percent of drink.volume_total_ml when it is in percent.';

-- ---------------------------------------------------------------------------
-- library_item
-- ---------------------------------------------------------------------------
--
-- Read-only base library shipped with the application (SPEC.md §5.4). Its
-- initial data set is the subject of issue #10; this migration only creates the
-- table.

CREATE TABLE library_item (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    category library_item_category NOT NULL,
    default_abv_percent double precision NOT NULL
        CHECK (default_abv_percent >= 0 AND default_abv_percent <= 100),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive, because the search of SPEC.md §5.4 is by name and a library
-- holding both "Vodka" and "vodka" would be a data entry accident.
CREATE UNIQUE INDEX library_item_lower_name_key ON library_item (lower(name));
