-- Initial alcoLoco schema (SPEC.md §4 and §7).
--
-- Conventions applied to every table below:
--
--   * primary keys are of type `uuid` and hold a **UUID v7 generated by the
--     application** (crate `uuid`, feature `v7`). PostgreSQL 16 ships no native
--     `uuidv7()`, so no column has a default: the caller always supplies the
--     identifier. v7 is time ordered, which makes it directly usable as a
--     pagination cursor;
--   * every point in time is a `timestamptz` stored in UTC. No local time and no
--     naive timestamp ever reaches the database (SPEC.md §7);
--   * durations are whole seconds in an `integer` column suffixed `_seconds`.
--     `interval` would allow month-based values, which have no meaning here and
--     are awkward to map back to the `f64` seconds the computation engine uses;
--   * volumes are millilitres (`_ml`), the unit of the reference formula of
--     SPEC.md §6.1. The cL / % choice offered to the user is a presentation and
--     input concern carried by `quantity_unit`;
--   * physical quantities are `double precision`, the exact type the computation
--     engine works in, so that a stored value round-trips bit for bit and the
--     "deterministic and replayable" requirement of SPEC.md §7 holds;
--   * there is deliberately **no `beta` column**: the elimination rate is a
--     constant of the `domain` crate, neither profile data nor an API field
--     (SPEC.md §10.0-H);
--   * no age is stored anywhere: `profile_settings_version` carries the birth
--     date and the age is derived at ingestion time (SPEC.md §10.0-K).

-- ---------------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------------

-- Sexes distinguished by the Watson equations (SPEC.md §6.2). The model has
-- exactly two branches, hence exactly two values.
CREATE TYPE sex AS ENUM ('male', 'female');

-- How the quantity of every component of a drink is expressed. The choice is
-- made per drink (SPEC.md §5.3).
CREATE TYPE quantity_unit AS ENUM ('cl', 'percent');

-- SPEC.md §5.4: the base library holds alcohols and soft drinks.
CREATE TYPE library_item_category AS ENUM ('alcohol', 'soft');

-- ---------------------------------------------------------------------------
-- Shared triggers
-- ---------------------------------------------------------------------------

CREATE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION set_updated_at() IS
    'Keeps updated_at truthful whatever the writer, instead of trusting every caller.';

-- ---------------------------------------------------------------------------
-- profile
-- ---------------------------------------------------------------------------
--
-- Identity plus the input preferences. The physiological parameters (weight,
-- height, sex, birth date) live in `profile_settings_version` and nowhere else:
-- they are exactly the versioned parameters, and duplicating a "current" copy
-- here would create two sources of truth able to contradict each other. The
-- current values of a profile are the ones of `profile_settings_at(id, now())`,
-- and the deferred constraint below guarantees that query always returns a row.
--
-- Input preferences are *not* versioned (SPEC.md §10.0-J): they enter no
-- computation, only the pre-filling of the entry form, so they stay here.

CREATE TABLE profile (
    id uuid PRIMARY KEY,
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    default_quantity_unit quantity_unit NOT NULL,
    default_ingestion_duration_seconds integer NOT NULL
        CHECK (default_ingestion_duration_seconds >= 0),
    default_absorption_duration_seconds integer NOT NULL
        CHECK (default_absorption_duration_seconds > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE profile IS
    'Predefined profile (no authentication in V1): identity and non-versioned input preferences.';
COMMENT ON COLUMN profile.id IS 'UUID v7 generated by the application.';
COMMENT ON COLUMN profile.default_absorption_duration_seconds IS
    'Strictly positive: a null absorption duration degenerates the trapezoidal profile of SPEC.md §6.4.';

CREATE TRIGGER profile_set_updated_at
    BEFORE UPDATE ON profile
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- profile_settings_version
-- ---------------------------------------------------------------------------
--
-- Time-stamped snapshot of the physiological parameters of a profile.
--
-- "No overlap and no gap" (SPEC.md §5.1, §10.0-J) is obtained structurally
-- rather than by a constraint: a version stores its **lower bound only**. The
-- upper bound of a version is the `valid_from` of the next one, so two versions
-- can neither overlap nor leave a hole by construction — the schema simply
-- cannot represent either. `UNIQUE (profile_id, valid_from)` completes the
-- picture by forbidding two versions starting at the very same instant, which
-- is the only remaining way to make the sequence ambiguous.
--
-- The oldest version has an open lower bound: `profile_settings_at()` below
-- falls back to it for any instant earlier than the whole sequence, so a drink
-- ingested before any recorded change always finds an applicable version.
--
-- Two rules stay on the application side, where they belong:
--   * `valid_from` may not be in the future — a CHECK cannot call `now()`,
--     which is not immutable;
--   * posting a version at T replaces every version strictly later than T
--     (SPEC.md §5.1). That is a write policy, implemented by issue #7.

CREATE TABLE profile_settings_version (
    id uuid PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    valid_from timestamptz NOT NULL,
    weight_kg double precision NOT NULL CHECK (weight_kg > 0 AND weight_kg < 1000),
    height_cm double precision NOT NULL CHECK (height_cm > 0 AND height_cm < 300),
    sex sex NOT NULL,
    birth_date date NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT profile_settings_version_unique_start UNIQUE (profile_id, valid_from)
);

COMMENT ON TABLE profile_settings_version IS
    'Versioned physiological parameters. A version stores its lower bound only; the upper bound is the next valid_from.';
COMMENT ON COLUMN profile_settings_version.valid_from IS
    'Effective date supplied by the user (SPEC.md §10.0-J); may be retroactive, never in the future.';
COMMENT ON COLUMN profile_settings_version.birth_date IS
    'Birth date, not an age: the age used by Watson is computed at the ingestion time of each drink (SPEC.md §10.0-K).';

-- ---------------------------------------------------------------------------
-- Every profile has at least one settings version
-- ---------------------------------------------------------------------------
--
-- Weight, height, sex and birth date are all mandatory (SPEC.md §10.0-D). Since
-- they live in `profile_settings_version`, "mandatory" means a profile must
-- always own at least one version. A plain foreign key cannot express that
-- without a cycle, so the guarantee is a DEFERRABLE constraint trigger checked
-- at commit: the profile and its first version are inserted in the same
-- transaction (the profile first, its foreign key is immediate), and the check
-- only fires once both statements have run.

CREATE FUNCTION assert_profile_settings_version_present() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    target_profile uuid;
BEGIN
    IF TG_OP = 'INSERT' THEN
        target_profile := NEW.id;
    ELSE
        target_profile := OLD.profile_id;
    END IF;

    -- The profile itself is gone (its versions were cascaded away): nothing to
    -- guarantee any more.
    IF NOT EXISTS (SELECT 1 FROM profile WHERE id = target_profile) THEN
        RETURN NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM profile_settings_version WHERE profile_id = target_profile
    ) THEN
        RAISE EXCEPTION 'profile % has no settings version', target_profile
            USING ERRCODE = 'integrity_constraint_violation';
    END IF;

    RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER profile_requires_settings_version
    AFTER INSERT ON profile
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_profile_settings_version_present();

CREATE CONSTRAINT TRIGGER profile_settings_version_keeps_last
    AFTER DELETE ON profile_settings_version
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_profile_settings_version_present();

-- ---------------------------------------------------------------------------
-- Settings applicable at a given instant
-- ---------------------------------------------------------------------------
--
-- Total function: it returns the latest version starting at or before `at`,
-- and falls back to the oldest version of the profile otherwise — that is the
-- open lower bound of SPEC.md §5.1. Combined with the trigger above, it returns
-- a row for every existing profile and every instant.

CREATE FUNCTION profile_settings_at(target_profile uuid, at timestamptz)
RETURNS profile_settings_version
LANGUAGE sql STABLE AS $$
    SELECT v.*
    FROM profile_settings_version AS v
    WHERE v.profile_id = target_profile
      AND v.valid_from = (
          SELECT coalesce(
              max(w.valid_from) FILTER (WHERE w.valid_from <= at),
              min(w.valid_from)
          )
          FROM profile_settings_version AS w
          WHERE w.profile_id = target_profile
      );
$$;

COMMENT ON FUNCTION profile_settings_at(uuid, timestamptz) IS
    'Physiological parameters in force at a given instant; falls back to the oldest version (open lower bound).';

-- ---------------------------------------------------------------------------
-- event
-- ---------------------------------------------------------------------------

CREATE TABLE event (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    starts_at timestamptz NOT NULL,
    ends_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT event_ends_after_it_starts CHECK (ends_at IS NULL OR ends_at >= starts_at)
);

COMMENT ON COLUMN event.ends_at IS
    'NULL for an open-ended event; the curve window is then min(now(), ends_at) + 3 h (SPEC.md §10.3).';

CREATE TRIGGER event_set_updated_at
    BEFORE UPDATE ON event
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- event_participant
-- ---------------------------------------------------------------------------
--
-- Pure association: its identity is the pair, so it carries no surrogate uuid.

CREATE TABLE event_participant (
    event_id uuid NOT NULL REFERENCES event (id) ON DELETE CASCADE,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    joined_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (event_id, profile_id)
);

CREATE INDEX event_participant_by_profile_idx ON event_participant (profile_id);

-- ---------------------------------------------------------------------------
-- drink
-- ---------------------------------------------------------------------------
--
-- A drink always belongs to the history of a profile; the link to an event is
-- optional (SPEC.md §4). The composite foreign key towards `event_participant`
-- states the stronger rule: when a drink *is* attached to an event, its profile
-- takes part in that event. It uses MATCH SIMPLE, so a NULL `event_id` skips the
-- check entirely — exactly the "optional attachment" semantics. Removing the
-- participant (or deleting the event, which cascades to the participants)
-- detaches the drinks instead of destroying them.

CREATE TABLE drink (
    id uuid PRIMARY KEY,
    profile_id uuid NOT NULL REFERENCES profile (id) ON DELETE CASCADE,
    event_id uuid,
    name text NOT NULL CHECK (btrim(name) <> ''),
    ingested_at timestamptz NOT NULL,
    ingestion_duration_seconds integer NOT NULL CHECK (ingestion_duration_seconds >= 0),
    absorption_duration_seconds integer NOT NULL CHECK (absorption_duration_seconds > 0),
    quantity_unit quantity_unit NOT NULL,
    volume_total_ml double precision CHECK (volume_total_ml > 0),
    feeling_rating smallint CHECK (feeling_rating BETWEEN 1 AND 10),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    -- SPEC.md §10.0-A: the total volume is mandatory as soon as quantities are
    -- expressed in %, and is otherwise *derived* from the sum of the components.
    -- Forbidding it in the cL case is what makes "never entered twice, never
    -- stored contradictory" a property of the schema rather than a convention.
    CONSTRAINT drink_volume_total_matches_unit CHECK (
        (quantity_unit = 'percent' AND volume_total_ml IS NOT NULL)
        OR (quantity_unit = 'cl' AND volume_total_ml IS NULL)
    ),

    CONSTRAINT drink_belongs_to_an_event_participant
        FOREIGN KEY (event_id, profile_id)
        REFERENCES event_participant (event_id, profile_id)
        ON DELETE SET NULL (event_id)
);

COMMENT ON COLUMN drink.volume_total_ml IS
    'Mandatory when quantity_unit = percent, NULL when cl (derived from the components) — SPEC.md §10.0-A.';
COMMENT ON COLUMN drink.feeling_rating IS
    'Optional feeling rating, 1 to 10 (SPEC.md §5.9). The 1-6 cap only applies to the value suggested by the app.';

CREATE INDEX drink_profile_history_idx ON drink (profile_id, ingested_at DESC);
CREATE INDEX drink_by_event_idx ON drink (event_id, profile_id);

CREATE TRIGGER drink_set_updated_at
    BEFORE UPDATE ON drink
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- drink_component
-- ---------------------------------------------------------------------------
--
-- Name, alcohol by volume and quantity (SPEC.md §4). In V1 a component typed by
-- hand is persisted in its drink only, with no personal library (SPEC.md §10.2),
-- so the name and the degree are copied here rather than referenced.

CREATE TABLE drink_component (
    id uuid PRIMARY KEY,
    drink_id uuid NOT NULL REFERENCES drink (id) ON DELETE CASCADE,
    sort_order integer NOT NULL CHECK (sort_order >= 0),
    name text NOT NULL CHECK (btrim(name) <> ''),
    abv_percent double precision NOT NULL CHECK (abv_percent >= 0 AND abv_percent <= 100),
    quantity double precision NOT NULL CHECK (quantity > 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT drink_component_unique_order UNIQUE (drink_id, sort_order)
);

COMMENT ON COLUMN drink_component.sort_order IS
    'Order in which the component was added. Breaks ties between equal volumes when naming a drink (SPEC.md §5.3, mode 2).';
COMMENT ON COLUMN drink_component.quantity IS
    'Millilitres when the parent drink is in cl, percent of drink.volume_total_ml when it is in percent.';

-- ---------------------------------------------------------------------------
-- library_item
-- ---------------------------------------------------------------------------
--
-- Read-only base library shipped with the application (SPEC.md §5.4). Its
-- initial data set is the subject of issue #10; this migration only creates the
-- table.

CREATE TABLE library_item (
    id uuid PRIMARY KEY,
    name text NOT NULL CHECK (btrim(name) <> ''),
    category library_item_category NOT NULL,
    default_abv_percent double precision NOT NULL
        CHECK (default_abv_percent >= 0 AND default_abv_percent <= 100),
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Case-insensitive, because the search of SPEC.md §5.4 is by name and a library
-- holding both "Vodka" and "vodka" would be a data entry accident.
CREATE UNIQUE INDEX library_item_lower_name_key ON library_item (lower(name));
