//! Identifiers generated by the API.
//!
//! Every row the API creates takes its primary key from here. PostgreSQL 16 has
//! no native `uuidv7()` and no column carries a default, so the ordering
//! property v7 provides is only real if every identifier goes through this one
//! function — a v4 slipped in somewhere would not fail, it would silently break
//! cursor pagination, which relies on that ordering (see [`crate::pagination`]).

use uuid::Uuid;

/// Generates the identifier of a row the API is about to create.
#[must_use]
pub fn new_id() -> Uuid {
    Uuid::now_v7()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_identifiers_the_api_generates_are_uuid_v7() {
        // Guards `new_id`, the only place the API mints an identifier.
        for _ in 0..64 {
            let id = new_id();
            assert_eq!(id.get_version_num(), 7, "{id} is not a UUID v7");
            assert_eq!(id.get_variant(), uuid::Variant::RFC4122, "{id}");
        }
    }

    #[test]
    fn the_identifiers_the_api_generates_sort_in_generation_order() {
        // The property cursor pagination rests on. Checked on a long burst
        // inside a single millisecond, which is the hard case: there the
        // ordering comes from the counter v7 keeps, not from the clock.
        let ids: Vec<Uuid> = (0..10_000).map(|_| new_id()).collect();
        for pair in ids.windows(2) {
            assert!(
                pair[0] < pair[1],
                "{} should sort before {}",
                pair[0],
                pair[1]
            );
        }
    }

    #[test]
    fn the_string_form_round_trips() {
        // A cursor travels as the textual form of an identifier; the two forms
        // have to agree or a page boundary lands on a different row.
        let id = new_id();
        assert_eq!(id.to_string().parse::<Uuid>().expect("must parse"), id);
    }
}
